# Site settings
title: Brompton Bike Hire
client:
  name: Brompton Bike Hire
  link: https://www.bromptonbikehire.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  We’ll send you to the gorgeous Belsfield Hotel, a grand period property set on the shimmering shores of Windemere. Enjoy a hearty breakfast each morning, before you pedal power your way around the irresistible Lakeland scenes.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/brompton-bike-hire" # the subpath of the site, including territory and year
img:     "/uk/2020/brompton-bike-hire/_assets/img"
css:     "/uk/2020/brompton-bike-hire/_assets/css"
js:      "/uk/2020/brompton-bike-hire/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed